from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime

class AttendanceLog(BaseModel):
    """Represents a single attendance event (check-in or check-out)."""

    # MongoDB ID (will be generated by the database)
    id: Optional[str] = Field(alias="_id", default=None)

    # Reference to the user who checked in
    user_id: str = Field(...)

    # Timestamp of the event
    timestamp: datetime = Field(default_factory=datetime.utcnow)

    # Type of event (e.g., 'check_in', 'check_out')
    # Default: 'check_in' for attendance system
    event_type: str = Field(default="check_in")

    # Status of the liveness check
    # Values: "pending", "passed", "failed"
    liveness: str = Field(default="pending")

    # Legacy field name (for backward compatibility)
    @property
    def liveness_status(self) -> str:
        return self.liveness

    class Config:
        populate_by_name = True
        json_encoders = {datetime: lambda dt: dt.isoformat()}
