from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime

class AttendanceLog(BaseModel):
    """Represents a single attendance event (check-in or check-out)."""

    # MongoDB ID (will be generated by the database)
    id: Optional[str] = Field(alias="_id", default=None)

    # Reference to the user who checked in
    user_id: str = Field(...)

    # Timestamp of the event
    timestamp: datetime = Field(default_factory=datetime.utcnow)

    # Type of event (e.g., 'check_in', 'check_out')
    event_type: str = Field(...)

    # Status of the liveness check
    liveness_status: str = Field(default="pending")

    class Config:
        # Allows the model to be created from MongoDB documents with '_id'
        populate_by_name = True
        # Custom JSON encoder to convert datetime to ISO string
        json_encoders = {datetime: lambda dt: dt.isoformat()}
